# Generated by Django 4.1.6 on 2023-02-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='pictureurl',
            new_name='picturedurl',
        ),
    ]
