# Generated by Django 4.1.6 on 2023-02-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0002_rename_pictureurl_item_picturedurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picturedurl',
        ),
        migrations.AddField(
            model_name='item',
            name='pictureurl',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
